# dist: focal
dist: xenial
# group: dev
# cirt: lxd

arch:
# - arm64
# - s390x
- amd64
# - ppc64le

rvm:
- 2.7.1
- 2.7.0
- 2.6.6
- 2.6.5
- 2.6.4
- 2.6.3

script:
- uname -a
- ruby -v
- docker run hello-world
# - dd if=/dev/zero of=file.txt count=1024 bs=30M
# - __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &
# - sleep 60
# - ruby -v

# # dist: xenial
# os: osx
# osx_image: xcode11.3
# language: ruby
# install: skip

# rvm:
# - 2.6.5
# - 2.7.0
# # - 2.7.1

# script:
# - uname -a
# - ruby -v


# # dist: focal
# # group: edge
# dist: xenial
# # group: dev

# arch:
# # - arm64
# # - s390x
# - amd64
# # - ppc64le

# # rvm:
# # - 2.7.1
# # - 2.7.0
# # - 2.6.6
# # - 2.6.5
# # - 2.6.4
# # - 2.6.3
# # - 2.6.2
# # - 2.6.1
# # - 2.6.0

# jobs:
#   include:
#     - stage: test
#       install: skip
#       script:
#       - ruby -v
#     - stage: go
#       language: go
#       script:
#       - go version
# #     - stage: php
# #       language: php
# #       script:
# #       - ruby -v
